### ISSUE TITLE
没有fk_status方法，应该是fk_devicestatus?

### ISSUE THREAD

**Issue by arthit2021** [enomothem/Whoamifuck#1]
![图片](https://github.com/enomothem/Whoamifuck/assets/89758841/3a196bec-a8f9-4f4a-84d2-cb854fb561ff)

**Comment by enomothem** [comment]
感谢您的反馈，是的，函数确实没有被调用，因为它是旧函数名，我们对此进行了更正。https://github.com/enomothem/Whoamifuck/commit/2bf07a615dbe0b93ff32963da12b7380e6ea6779

**Comment by enomothem** [comment]
赋予编号：WHOK-2023-08230
