### ISSUE TITLE
[bug] WHOK-2024-05110 输出的html格式有点问题

### ISSUE THREAD

**Issue by dajjboom** [enomothem/Whoamifuck#12]
![image](https://github.com/enomothem/Whoamifuck/assets/35320507/2d1c30ea-f3b2-4b0d-ab1d-f6e04a75211d)
从进程开始下面的字全部带横杠了

**Comment by dajjboom** [comment]
原因是打印的进程信息带有<>等转义标签符号了，帮你改下
process_info=$(ps aux | sed -e 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g; s/"/\&quot;/g; s/'\''/\&#39;/g')

**Comment by enomothem** [comment]
感谢@dajjboom的issue，尖括号确实会影响`<pre>`标签，目前只发现<>导致的问题，已将尖括号转义为实体编码，麻烦再次测试是否能正常解析。
```
process_info=$(ps aux | sed -e 's/</\&lt;/g; s/>/\&gt;/g')
```

**Comment by enomothem** [comment]
https://github.com/enomothem/Whoamifuck/commit/92641dfbdd1c53aedc0f7ff9103d8b9e7556b227 赋予编号 WHOK-2024-05110
