### ISSUE TITLE
腾讯云lh列端口有点问题

### ISSUE THREAD

**Issue by sunu11** [enomothem/Whoamifuck#13]
## 开启端口列表
function fk_portstatus
{
    PORT=`netstat -tunlp | awk '/^tcp/ {print $4,$7}; /^udp/ {print $4,$6}' | sed -r 's/.*:(.*)\/.*/\1/' | sort -un | awk '{cmd = "sudo lsof -w -i :" $1 " | awk '\''NR==2{print $1}'\''"; cmd | getline serviceName; close(cmd); print $1 "\t" serviceName}'`
    bar
    echo
    printf "%s\n" "$bar_port_open"
    echo
    printf "%s\n" "$PORT"
}

这部分，我在机器上运行
netstat -tunlp | awk '/^tcp/ {print $4,$7}; /^udp/ {print $4,$6}' | sed -r 's/.*:(.*)\/.*/\1/' | sort -un 
是能够把端口输出的，但是执行netstat -tunlp | awk '/^tcp/ {print $4,$7}; /^udp/ {print $4,$6}' | sed -r 's/.*:(.*)\/.*/\1/' | sort -un | awk '{cmd = "sudo lsof -w -i :" $1 " | awk '\''NR==2{print $1}'\''"; cmd | getline serviceName; close(cmd); print $1 "\t" serviceName}' 就卡住了。
![image](https://github.com/enomothem/Whoamifuck/assets/23350775/87c4b3bf-31a6-455f-8e4d-8af5a96d2a2c)

**Comment by enomothem** [comment]
能发个联系方式吗

**Comment by sunu11** [comment]
您好  您的邮件已收到。稍后给您回复。

**Comment by sunu11** [comment]
老哥，你加我微信：Su7top

**Comment by enomothem** [comment]
经过考虑，该功能可能与主机的配置性能有关，并不影响输出。

当然，也考虑在html输出中使用ss增强输出的结果。

**Comment by sunu11** [comment]
您好  您的邮件已收到。稍后给您回复。
