### ISSUE TITLE
updateDescriptionAndSuggestion 想了解这个方法原本的设计思路

### ISSUE THREAD

**Issue by CGerAJ** [enomothem/Whoamifuck#14]
目前直接输出的有安全问题
看了html是模拟数据

**Comment by enomothem** [comment]
@CGerAJ 没明白你的意思，HTML删除的是一些打印的信息和经过处理后的分析数据来帮助排查，会经过分析得出一些初步的风险提示，本事不存在什么安全问题，HTML也不是模拟数据。
