### ISSUE TITLE
[bug]  WHOK-2024-06280 -u参数：用户基本信息返回结果不一致

### ISSUE THREAD

**Issue by xmqaq** [enomothem/Whoamifuck#16]
工具运行返回信息：
![WechatIMG1135](https://github.com/enomothem/Whoamifuck/assets/50257557/45fff2e7-d6e2-477f-8928-674904d06dec)

**Comment by enomothem** [comment]
这个机器是不是没有ifconfig命令

**Comment by xmqaq** [comment]
有的，特意安装了;运行命令后，没安装脚本会报错的。（我的环境是ubuntu20.4）

**Comment by xmqaq** [comment]
> 这个机器是不是没有ifconfig命令

有的，特意安装了;运行命令后，没安装脚本会报错的。（我的环境是ubuntu20.4）

**Comment by enomothem** [comment]
> > 这个机器是不是没有ifconfig命令
> 
> 有的，特意安装了;运行命令后，没安装脚本会报错的。（我的环境是ubuntu20.4）

@xmqaq  首先非常感谢提出这个问题。是的，这是我预料的问题，因为目前大部分机器都预装了net-tools工具包，如果没有只能使用ip a 命令查看，我下个版本做一个判断，如果没有ifconfig命令将使用ip a代替，这样兼容性会好很多。

**Comment by enomothem** [comment]
赋予编号 WHOK-2024-06280 @xmqaq
