### ISSUE TITLE
[bug] WHOK-2024-07090 chkrookit 检测名称错误

### ISSUE THREAD

**Issue by RaiderZP** [enomothem/Whoamifuck#18]
Hi, 在使用chkrootkit检测时会提前检测是否安装chkrootkit，但是检测安装时用的名称是chkrookit而不是chkrootkit，导致在接下来的安装时会失败，无法定位该软件名称
![image](https://github.com/enomothem/Whoamifuck/assets/38402326/13cc0c04-2a92-4628-a0ae-e81ae99f7a02)

**Comment by enomothem** [comment]
感谢师傅，已修改
