### ISSUE TITLE
导出不了数据请问是为什么呢

### ISSUE THREAD

**Issue by lydiaGoGO** [enomothem/Whoamifuck#21]
我看默认的导出路径是output/html 加了参数-m 1.html，但是实际上并没有文件被生成，生成文件的函数也没有被调用fk_reporthtml

**Comment by enomothem** [comment]
![image](https://github.com/user-attachments/assets/88e6cc40-1db2-442f-90a8-a6fa583663ea)
没有问题，请问你是什么系统、内核版本、以及是否在生成报告的时候遇到报错或意外退出。

**Comment by lydiaGoGO** [comment]
![Uploading 微信截图_20241101105121.png…]()

**Comment by lydiaGoGO** [comment]
![微信截图_20241101105121](https://github.com/user-attachments/assets/e0f62d1c-cee6-4909-88a3-e7986af1ad72)

**Comment by lydiaGoGO** [comment]
我知道了，只能跟一个参数OTZ，是我没看清楚

**Comment by enomothem** [comment]
好的，如果使用中还要什么问题随时提ISSUE。
