### ISSUE TITLE
执行时没有-f 参数

### ISSUE THREAD

**Issue by tysmlq** [enomothem/Whoamifuck#3]
说明手册里面有-f 指定文件，但实际执行没有-f参数。
比如默认对/var/log/auth.log检查，但centos下没有该文件，因此无法手工指定要检测的日志文件

**Comment by enomothem** [comment]
@tysmlq 感谢您的反馈，由于自述文档并没有更新，处于老版本的`-f`参数进行判断的，目前版本使用`-l`参数指定文件，或不指定文件，根据判断操作系统自动读取相应的文件。如centos则是/var/log/secure。

README.md已经更新，请查看最新文档。
