### ISSUE TITLE
[feat] 优化建议

### ISSUE THREAD

**Issue by Surbo666** [enomothem/Whoamifuck#4]
1.主程序“whoamifuck”可编写超过阈值自动告警程序，帮助运维人员更方便发现问题
2.当前基于系统日志判断，可根据规则进行基线核查
3.RHEL 8不再支持pam_tally2，故pam_tally2.so文件缺失，可更换为pam_faillock.so
4.可合入自动执行代码

**Comment by enomothem** [comment]
哇哦~👍 这个思路不错哟
